### ISSUE TITLE
Terraform Aqua provider doesn't properly destroy "aquasec_enforcer_groups"

### ISSUE THREAD

**Issue by ruzickap** [aquasecurity/terraform-provider-aquasec#156]
Terraform Aqua provider doesn't properly destroy "aquasec_enforcer_groups".

This issue should be fixed here https://github.com/aquasecurity/terraform-provider-aquasec/issues/135, but it wasn't.
(this time I updated the aqusec provider to latest v0.8.12 to verify it)

### Terraform Version

```bash
❯ terraform -v
Terraform v1.2.2
on darwin_amd64
+ provider registry.terraform.io/aquasecurity/aquasec v0.8.12
```

### Affected Resource(s)
- aquasec_enforcer_groups

### Steps to Reproduce

I'm using this code to create enforcer groups in Aqua:

```hcl
terraform {
  backend "local" {
    path = "terraform.tfstate"
  }
  required_providers {
    aquasec = {
      version = "0.8.12"
      source  = "aquasecurity/aquasec"
    }
  }
}

provider "aquasec" {
  username = var.aquasec_username
  aqua_url = var.aquasec_url
  password = var.aquasec_password
}

variable "aquasec_username" {
  type        = string
  description = "Aqua Username"
}

variable "aquasec_password" {
  type        = string
  description = "Aqua Password"
}

variable "aquasec_url" {
  type        = string
  description = "Aqua URL"
}

resource "aquasec_enforcer_groups" "auqa-enforcers-agent-kubernetes" {
  group_id    = "tes-enforcer"
  type        = "agent"
  description = "Test Enforcer"
  enforce     = true
  # Host Assurance
  host_assurance = true
  # Network Firewall (Host Protection)
  host_network_protection = true
  # Runtime Controls
  host_protection = true
  # Network Firewall (Container Protection)
  network_protection = true
  # Advanced Malware Protection (Container Protection)
  container_antivirus_protection = true
  # Runtime Controls
  container_activity_protection = true
  # Image Assurance
  image_assurance = true
  # Advanced Malware Protection (Host Protection)
  antivirus_protection = true
  # Host Images
  sync_host_images = true
  # Risk Explorer
  risk_explorer_auto_discovery = true

  orchestrator {
    type      = "kubernetes"
    namespace = "aqua"
  }
}

resource "aquasec_enforcer_groups" "auqa-enforcers-kube_enforcers-kubernetes" {
  group_id    = "test-kube_enforcer"
  type        = "kube_enforcer"
  description = "Test Kube Enforcer"
  enforce     = true
  # Enable admission control
  admission_control = true
  # Perform admission control if not connected to a gateway
  block_admission_control = true
  # Enable workload discovery
  auto_discovery_enabled = true
  # Register discovered pod images
  auto_scan_discovered_images_running_containers = true
  # Add discovered registries
  auto_discover_configure_registries = true
  # Kube-bench image path
  kube_bench_image_name = "registry.aquasec.com/kube-bench:v0.6.5"
  # Secret that holds the registry credentials for the Pod Enforcer and kube-bench
  micro_enforcer_secrets_name = "aqua-registry"
  # Auto copy these secrets to the Pod Enforcer namespace and container
  auto_copy_secrets = true

  orchestrator {
    type      = "kubernetes"
    namespace = "aqua"
  }
}
```

Install kube-enforcer to k8s cluster:

```
helm repo add aqua-helm https://helm.aquasec.com
helm upgrade --install --version "2022.4.5" --namespace aqua --create-namespace --values - kube-enforcer aqua-helm/kube-enforcer << EOF
global:
  enforcer:
    enabled: true
  gateway:
    address: 25dxxxxxxxx-gw.cloud.aquasec.com
    port: 443
  imageCredentials:
  imageCredentials:
    create: true
    #---# Aqua repository example:
    username: "xxxxxxxxxxxxxx"
    password: "xxxxxxxxxxxxxx"
serviceAccount:
  create: true
clusterName: "kube2.k8s.mylabs.com"
logicalName: "kube2.k8s.mylabs.com"
certsSecret:
  autoGenerate: true
aquaSecret:
  #---# The following value needs to be changed !
  kubeEnforcerToken: "xxxxxxx"
enforcer:
  #---# The following value needs to be changed !
  enforcerToken: "xxxxxxxxxxx"
  logicalName: kube2.k8s.mylabs.com
  nodeName: kube2.k8s.mylabs.com
EOF
```

Once the enforcer groups are create I connected my k8s cluster and everything is working like expected: 

![image](https://user-images.githubusercontent.com/1434387/175023037-332daffa-89ee-4eb2-beb0-799ccaa6ace5.png)

The problem appeared when I tried to run `terraform destroy` where I'm getting:

```text
aquasec_enforcer_groups.auqa-enforcers-kube_enforcers-kubernetes: Destroying... [id=test-kube_enforcer]
aquasec_enforcer_groups.auqa-enforcers-agent-kubernetes: Destroying... [id=tes-enforcer]
╷
│ Error: failed deleting enforcer group, status code: 400
│
│
╵
╷
│ Error: failed deleting enforcer group, status code: 400
```

When I delete the k8s cluster I can not destroy it either (see "red" disconnected enforcers):

![image](https://user-images.githubusercontent.com/1434387/175026991-a809fae8-10a4-4eb1-9814-8a97cb583163.png)

I need to manually delete connections/enforcers in Aqua GUI and then I can destroy it:

![image](https://user-images.githubusercontent.com/1434387/175027768-0003cdc7-d76e-49e1-ab31-127140aa85c7.png)

-> Terraform should be able to destroy enforcer groups without any manual intervention.

---

Use case - we are creating / deleting k8s clusters for testing purposes therefore we would like to automate the whole process:
* create cluster 
* register cluster to Aqua 
* run tests
* delete cluster 
* delete cluster form Aqua
